# Generated by Django 2.2.15 on 2020-08-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_gjkhkjhkj"),
    ]

    operations = [
        migrations.AddField(
            model_name="gjkhkjhkj",
            name="hgfhgfhgfghfghf",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gjkhkjhkj",
            name="hjgjhgjgjgjgjh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="gjkhkjhkj",
            name="jhgjhgjhgjfhgh",
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
